blueprint:
  name: Podcast Hub - Notify on New Episode
  description: Notify when a specific podcast feed publishes a new episode.
  domain: automation
  input:
    feed_sensor:
      name: Podcast feed sensor
      description: The Podcast Hub sensor to watch for new episodes.
      selector:
        entity:
          domain: sensor
          integration: podcast_hub

mode: single

variables:
  feed_sensor: !input feed_sensor
  feed_id: >-
    {% set attr_id = state_attr(feed_sensor, 'feed_id') %}
    {% if attr_id %}
      {{ attr_id }}
    {% else %}
      {{ feed_sensor.split('sensor.podcast_')[-1] }}
    {% endif %}

trigger:
  - platform: event
    event_type: podcast_hub_new_episode

condition:
  - condition: template
    value_template: "{{ trigger.event.data.feed_id == feed_id }}"

action:
  - service: persistent_notification.create
    data:
      title: >-
        New episode: {{ trigger.event.data.feed_title }}
      message: >-
        {{ trigger.event.data.episode.title }}
