blueprint:
  name: Podcast Hub - Play Latest Episode
  description: Play the latest episode of a Podcast Hub feed on a media player.
  domain: automation
  input:
    feed_sensor:
      name: Podcast feed sensor
      description: The Podcast Hub sensor for the feed to play.
      selector:
        entity:
          domain: sensor
    media_player:
      name: Media player
      description: The media player to play the latest episode.
      selector:
        entity:
          domain: media_player

mode: single

variables:
  feed_sensor: !input feed_sensor
  media_player: !input media_player
  feed_id: "{{ feed_sensor.split('sensor.podcast_')[-1] }}"
  episodes: "{{ state_attr(feed_sensor, 'episodes') or [] }}"
  latest_guid: >-
    {% if episodes %}
      {{ episodes[0].guid }}
    {% else %}
      {{ none }}
    {% endif %}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ latest_guid is not none }}"
        sequence:
          - service: media_player.play_media
            target:
              entity_id: !input media_player
            data:
              media_content_id: >-
                media-source://podcast_hub/{{ feed_id }}/{{ latest_guid | urlencode }}
              media_content_type: podcast
